apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: contrib-collector-tempo-grpc
  namespace: tracing-system
spec:
  mode: deployment
  serviceAccount: otel-collector
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}

    processors:
      batch: {}

    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"

    exporters:
      # gRPC 到 Tempo Gateway（多租戶）
      otlp/tempo-grpc:
        endpoint: tempo-simplest-gateway.tracing-system.svc.cluster.local:8090
        tls:
          insecure: false
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: "dev"
        retry_on_failure:
          enabled: true
        sending_queue:
          enabled: true

      # 以 stdout 輸出 spans 的新式 exporter
      debug/stdout:
        verbosity: detailed   # 可用: basic | normal | detailed

    service:
      extensions: [bearertokenauth]
      telemetry:
        logs:
          level: debug       # Collector 自身日誌層級
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo-grpc, debug/stdout]
